name: lando-nginx-121
services:
  defaults:
    type: nginx:1.21
    build_as_root:
      - apt-get update && apt-get install -y curl

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ./../../
