name: lando-nginx-117
services:
  defaults:
    type: nginx:1.17
  patch:
    type: nginx:1.17.10

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ../..
