name: lando-nginx-plugin
services:
  node:
    type: node:16
    build:
      - yarn install
    scanner: false
    ssl: false
    sslExpose: false
tooling:
  node:
    service: node
  yarn:
    service: node
