name: lando-nginx-worker-user
services:
  web:
    type: nginx:1.29
    webroot: www
    build_as_root:
      - apt-get update && apt-get install -y curl
      - mkdir -p /app/www
      - echo "hello" > /app/www/index.html
      - chown -R www-data:www-data /app/www
      - chmod 750 /app/www
      - chmod 640 /app/www/index.html

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ../..
