name: lando-nginx-116
services:
  defaults:
    type: nginx:1.16
  patch:
    type: nginx:1.16.1

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ../..
