name: lando-nginx-124
services:
  defaults:
    type: nginx:1.24

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ./../../
