name: lando-nginx-custom
services:
  custom:
    type: nginx:1.25
    ssl: true
    webroot: www
    build_as_root:
      - apt-get update && apt-get install -y curl
    config:
      server: config/server2.conf
      vhosts: config/custom.conf
      params: config/params
  custom_116:
    type: nginx:1.16
    ssl: true
    webroot: www
    config:
      server: config/server2.conf
      vhosts: config/custom.conf
      params: config/params

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ../..
