name: lando-nginx-118
services:
  defaults:
    type: nginx:1.18

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ../..
