name: lando-nginx-119
services:
  defaults:
    type: nginx:1.19

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/nginx": ./../../
