name: Nginx Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        lando-version:
          - 3-dev-slim
        os:
          - ubuntu-22.04
        node-version:
          - '16'
        leia-test:
          - examples/1.16
          - examples/1.17
          - examples/1.18
          - examples/1.19
          - examples/1.20
          - examples/1.21
          - examples/1.22
          - examples/1.23
          - examples/1.24
          - examples/1.25
          - examples/custom

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install NPM dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/nginx=/home/runner/work/nginx/nginx
          telemetry: false
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
